import type { Metadata } from "next";
import { Fira_Mono as FontSans } from "next/font/google";
import "./globals.css";
import { EditorContainer, Logo, Menu } from "@/components";
import { cn } from "@/utils/styles";

const fontSans = FontSans({
  weight: ["400", "500", "700"],
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <EditorContainer>
          <header className="h-14 border-b border-editor-divider flex items-center">
            <Logo />
            <Menu />
          </header>
          {children}
        </EditorContainer>
      </body>
    </html>
  );
}
